<?php

namespace App\Core\Routes;

use App\Core\Controllers\Api\AdminController;
use App\Core\Controllers\Api\LanguageController;
use App\Core\Controllers\Api\RegionGroupController;
use App\Core\Controllers\Api\RegionController;
use App\Core\Controllers\Api\CountryController;
use App\Core\Controllers\Api\CurrencyController;
use App\Core\Controllers\Api\SiteController;
use App\Core\Controllers\Api\LengthTypeController;
use App\Core\Controllers\Api\WeightTypeController;
use App\Core\Controllers\Api\TaxController;
use App\Core\Controllers\Api\SubscriptionController;
use App\Core\Controllers\Api\PostController;
use App\Core\Controllers\Api\TaxonomyController;
use App\Core\Controllers\Api\CommentController;
use App\Core\Controllers\Api\ComponentController;
use App\Core\Controllers\Api\ListController;
use App\Core\Controllers\Api\MediaController;
use App\Core\Controllers\Api\RoleController;
use App\Core\Controllers\Api\PostTypeController;
use App\Core\Controllers\Api\ProductTypeController;
use App\Core\Controllers\Api\StatusController;
use App\Core\Controllers\Api\UserController;
use App\Core\Controllers\Api\UserGroupController;
use App\Core\Controllers\Api\TagController;
use App\Core\Controllers\Api\ModelController;
use App\Core\Controllers\Api\ProductController;
use App\Core\Controllers\Api\ProjectController;
use App\Core\Controllers\Api\PageController;
use App\Core\Controllers\Api\QuoteController;
use App\Core\Controllers\Api\OrderController;
use App\Core\Controllers\Api\QuoteItemController;
use App\Core\Controllers\Api\OrderItemController;
use App\Core\Controllers\Api\JobController;
use App\Core\Controllers\Api\ProductQuestionController;
use App\Core\Controllers\Api\ProductReviewController;
use App\Core\Controllers\Api\PostTagController;
use App\Core\Controllers\Api\CouponController;
use App\Core\Controllers\Api\CouponItemController;
use App\Core\Controllers\Api\DesignResourceController;
use App\Core\Controllers\Api\PinboardController;
use App\Core\Controllers\Api\PinboardItemController;
use App\Core\Controllers\Api\TaxonomyItemController;
use App\Core\Models\Admin\Admin;
use App\Core\Models\PostCategory\TaxonomyItem;
use App\Core\Routes\Base\Api;
use App\Core\System\Event;

use function App\Core\System\utils\controller;

class ApiRoute extends Api{
    public static array $routes = [
        [
            'method' => 'GET',
            'uri' => '/api/languages',
            'controller' => LanguageController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/languages/{id}',
            'controller' => LanguageController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/languages',
            'controller' => LanguageController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/languages/{id}',
            'controller' => LanguageController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/languages/{id}',
            'controller' => LanguageController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/region-groups',
            'controller' => RegionGroupController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/region-groups/{id}',
            'controller' => RegionGroupController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/region-groups',
            'controller' => RegionGroupController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/region-groups/{id}',
            'controller' => RegionGroupController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/region-groups/{id}',
            'controller' => RegionGroupController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/regions',
            'controller' => RegionController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/regions/{id}',
            'controller' => RegionController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/regions',
            'controller' => RegionController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/regions/{id}',
            'controller' => RegionController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/regions/{id}',
            'controller' => RegionController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/countries',
            'controller' => CountryController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/countries/{id}',
            'controller' => CountryController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/countries',
            'controller' => CountryController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/countries/{id}',
            'controller' => CountryController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/countries/{id}',
            'controller' => CountryController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/currencies',
            'controller' => CurrencyController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/currencies/{id}',
            'controller' => CurrencyController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/currencies',
            'controller' => CurrencyController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/currencies/{id}',
            'controller' => CurrencyController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/currencies/{id}',
            'controller' => CurrencyController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/sites',
            'controller' => SiteController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/sites/{id}',
            'controller' => SiteController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/sites',
            'controller' => SiteController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/sites/{id}',
            'controller' => SiteController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/sites/{id}',
            'controller' => SiteController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/length-types',
            'controller' => LengthTypeController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/length-types/{id}',
            'controller' => LengthTypeController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/length-types',
            'controller' => LengthTypeController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/length-types/{id}',
            'controller' => LengthTypeController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/length-types/{id}',
            'controller' => LengthTypeController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/weight-types',
            'controller' => WeightTypeController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/weight-types/{id}',
            'controller' => WeightTypeController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/weight-types',
            'controller' => WeightTypeController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/weight-types/{id}',
            'controller' => WeightTypeController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/weight-types/{id}',
            'controller' => WeightTypeController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-rates',
            'controller' => TaxController::class,
            'action' => 'rateIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-rates/{id}',
            'controller' => TaxController::class,
            'action' => 'rateShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/tax-rates',
            'controller' => TaxController::class,
            'action' => 'rateCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/tax-rates/{id}',
            'controller' => TaxController::class,
            'action' => 'rateUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/tax-rates/{id}',
            'controller' => TaxController::class,
            'action' => 'rateDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-rules',
            'controller' => TaxController::class,
            'action' => 'ruleIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-rules/{id}',
            'controller' => TaxController::class,
            'action' => 'ruleShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/tax-rules',
            'controller' => TaxController::class,
            'action' => 'ruleCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/tax-rules/{id}',
            'controller' => TaxController::class,
            'action' => 'ruleUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/tax-rules/{id}',
            'controller' => TaxController::class,
            'action' => 'ruleDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-types',
            'controller' => TaxController::class,
            'action' => 'typeIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/tax-types/{id}',
            'controller' => TaxController::class,
            'action' => 'typeShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/tax-types',
            'controller' => TaxController::class,
            'action' => 'typeCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/tax-types/{id}',
            'controller' => TaxController::class,
            'action' => 'typeUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/tax-types/{id}',
            'controller' => TaxController::class,
            'action' => 'typeDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscriptions',
            'controller' => SubscriptionController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscriptions/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/subscriptions',
            'controller' => SubscriptionController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/subscriptions/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/subscriptions/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscription-plans',
            'controller' => SubscriptionController::class,
            'action' => 'planIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscription-plans/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'planShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/subscription-plans',
            'controller' => SubscriptionController::class,
            'action' => 'planCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/subscription-plans/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'planUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/subscription-plans/{id}',
            'controller' => SubscriptionController::class,
            'action' => 'planDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/posts',
            'controller' => PostController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/posts/{id}',
            'controller' => PostController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/posts',
            'controller' => PostController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/posts/{id}',
            'controller' => PostController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/posts/{id}',
            'controller' => PostController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/posts/delete-image/{post_image_id}',
            'controller' => PostController::class,
            'action' => 'deletePostImage',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/posts/{post_id}/upload',
            'controller' => PostController::class,
            'action' => 'upload',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/posts-statuses',
            'controller' => PostController::class,
            'action' => 'getStatuses',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/posts-import',
            'controller' => PostController::class,
            'action' => 'importPosts',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/post-image-import',
            'controller' => PostController::class,
            'action' => 'importPostImages',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-tags',
            'controller' => PostTagController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-tags/{id}',
            'controller' => PostTagController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/post-tags',
            'controller' => PostTagController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/post-tags/{id}',
            'controller' => PostTagController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/post-tags/{id}',
            'controller' => PostTagController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pages',
            'controller' => PageController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pages/{id}',
            'controller' => PageController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/pages',
            'controller' => PageController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/pages/{id}',
            'controller' => PageController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/pages/{id}',
            'controller' => PageController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pages-statuses',
            'controller' => PageController::class,
            'action' => 'getStatuses',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-tags',
            'controller' => TagController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-tags/{id}',
            'controller' => TagController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/post-tags',
            'controller' => TagController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/post-tags/{id}',
            'controller' => TagController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/post-tags/{id}',
            'controller' => TagController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/taxonomies',
            'controller' => TaxonomyController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/taxonomies/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/taxonomies',
            'controller' => TaxonomyController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/taxonomies/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/taxonomies/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/category-import',
            'controller' => TaxonomyController::class,
            'action' => 'importTaxonomyItems',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/comments',
            'controller' => CommentController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/comments/{id}',
            'controller' => CommentController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/comments',
            'controller' => CommentController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/comments/{id}',
            'controller' => CommentController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/comments/{id}',
            'controller' => CommentController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-questions',
            'controller' => ProductQuestionController::class,
            'action' => 'index',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/product-questions/{id}',
            'controller' => ProductQuestionController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/product-questions/{id}',
            'controller' => ProductQuestionController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-reviews',
            'controller' => ProductReviewController::class,
            'action' => 'index',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/product-reviews/{id}',
            'controller' => ProductReviewController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/product-reviews/{id}',
            'controller' => ProductReviewController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media',
            'controller' => MediaController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media/{id}',
            'controller' => MediaController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media/upload',
            'controller' => MediaController::class,
            'action' => 'upload',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media/upload-to-folder/{folder_id}',
            'controller' => MediaController::class,
            'action' => 'uploadToFolder',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media/delete-by-filename',
            'controller' => MediaController::class,
            'action' => 'deleteByFilename',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media/delete-by-path',
            'controller' => MediaController::class,
            'action' => 'deleteByPath',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media-folders',
            'controller' => MediaController::class,
            'action' => 'getFolders',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media-folders/{id}',
            'controller' => MediaController::class,
            'action' => 'getSubFolders',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media-files',
            'controller' => MediaController::class,
            'action' => 'getFiles',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media-files/{id}',
            'controller' => MediaController::class,
            'action' => 'getFiles',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/media-folders',
            'controller' => MediaController::class,
            'action' => 'createFolder',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/media-folders/{id}',
            'controller' => MediaController::class,
            'action' => 'deleteFolder',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/media/files/{id}',
            'controller' => MediaController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/media-categories',
            'controller' => MediaController::class,
            'action' => 'getCategories',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/roles',
            'controller' => RoleController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/roles/{id}',
            'controller' => RoleController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/roles',
            'controller' => RoleController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/roles/{id}',
            'controller' => RoleController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/roles/{id}',
            'controller' => RoleController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-types',
            'controller' => PostTypeController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/post-types/{id}',
            'controller' => PostTypeController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/post-types',
            'controller' => PostTypeController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/post-types/{id}',
            'controller' => PostTypeController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/post-types/{id}',
            'controller' => PostTypeController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/finishes-import',
            'controller' => DesignResourceController::class,
            'action' => 'importFinishes',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/textiles-import',
            'controller' => DesignResourceController::class,
            'action' => 'importTextiles',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/colors-import',
            'controller' => DesignResourceController::class,
            'action' => 'importColors',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/documents-import',
            'controller' => DesignResourceController::class,
            'action' => 'importDocuments',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/models-import',
            'controller' => DesignResourceController::class,
            'action' => 'importModels',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/projects',
            'controller' => ProjectController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/projects/{id}',
            'controller' => ProjectController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/projects',
            'controller' => ProjectController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/projects/{id}',
            'controller' => ProjectController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/projects/{id}',
            'controller' => ProjectController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/projects/delete-image/{project_image_id}',
            'controller' => ProjectController::class,
            'action' => 'deleteProjectImage',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/projects-statuses',
            'controller' => ProjectController::class,
            'action' => 'getStatuses',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/project-import',
            'controller' => ProjectController::class,
            'action' => 'importProjects',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/project-image-import',
            'controller' => ProjectController::class,
            'action' => 'importProjectImages',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/projects/{project_id}/upload',
            'controller' => ProjectController::class,
            'action' => 'upload',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/projects/delete-by-path',
            'controller' => ProjectController::class,
            'action' => 'deleteByPath',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/products',
            'controller' => ProductController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/products/{id}',
            'controller' => ProductController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/products',
            'controller' => ProductController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/products/{id}',
            'controller' => ProductController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/products/{id}',
            'controller' => ProductController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/products-categories',
            'controller' => ProductController::class,
            'action' => 'getCategories',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/products-list',
            'controller' => ProductController::class,
            'action' => 'productList',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/products-related-search',
            'controller' => ProductController::class,
            'action' => 'relatedProductSearch',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/products-variant-search',
            'controller' => ProductController::class,
            'action' => 'variantProductSearch',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/digital-asset-search',
            'controller' => ProductController::class,
            'action' => 'digitalAssetSearch',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-options',
            'controller' => ProductController::class,
            'action' => 'getOptions',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/products-import',
            'controller' => ProductController::class,
            'action' => 'importProducts',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-types',
            'controller' => ProductTypeController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-types/{id}',
            'controller' => ProductTypeController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/product-types',
            'controller' => ProductTypeController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/product-types/{id}',
            'controller' => ProductTypeController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/product-types/{id}',
            'controller' => ProductTypeController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/stock-statuses',
            'controller' => StatusController::class,
            'action' => 'stockStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/stock-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'stockStatusShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/stock-statuses',
            'controller' => StatusController::class,
            'action' => 'stockStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/stock-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'stockStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/stock-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'stockStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscription-statuses',
            'controller' => StatusController::class,
            'action' => 'subscriptionStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/subscription-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'subscriptionStatusShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/subscription-statuses',
            'controller' => StatusController::class,
            'action' => 'subscriptionStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/subscription-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'subscriptionStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/subscription-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'subscriptionStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/order-statuses',
            'controller' => StatusController::class,
            'action' => 'orderStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/order-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'orderStatusShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/order-statuses',
            'controller' => StatusController::class,
            'action' => 'orderStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/order-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'orderStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/order-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'orderStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/payment-statuses',
            'controller' => StatusController::class,
            'action' => 'paymentStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/payment-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'paymentStatusShow',
        ],  
        [
            'method' => 'POST',
            'uri' => '/api/payment-statuses',
            'controller' => StatusController::class,
            'action' => 'paymentStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/payment-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'paymentStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/payment-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'paymentStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/shipping-statuses',
            'controller' => StatusController::class,
            'action' => 'shippingStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/shipping-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'shippingStatusShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/shipping-statuses',
            'controller' => StatusController::class,
            'action' => 'shippingStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/shipping-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'shippingStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/shipping-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'shippingStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-statuses',
            'controller' => StatusController::class,
            'action' => 'returnStatusIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'returnStatusShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/return-statuses',
            'controller' => StatusController::class,
            'action' => 'returnStatusCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/return-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'returnStatusUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/return-statuses/{id}',
            'controller' => StatusController::class,
            'action' => 'returnStatusDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-resolutions',
            'controller' => StatusController::class,
            'action' => 'returnResolutionIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-resolutions/{id}',
            'controller' => StatusController::class,
            'action' => 'returnResolutionShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/return-resolutions',
            'controller' => StatusController::class,
            'action' => 'returnResolutionCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/return-resolutions/{id}',
            'controller' => StatusController::class,
            'action' => 'returnResolutionUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/return-resolutions/{id}',
            'controller' => StatusController::class,
            'action' => 'returnResolutionDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-reasons',
            'controller' => StatusController::class,
            'action' => 'returnReasonIndex',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/return-reasons/{id}',
            'controller' => StatusController::class,
            'action' => 'returnReasonShow',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/return-reasons',
            'controller' => StatusController::class,
            'action' => 'returnReasonCreate',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/return-reasons/{id}',
            'controller' => StatusController::class,
            'action' => 'returnReasonUpdate',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/return-reasons/{id}',
            'controller' => StatusController::class,
            'action' => 'returnReasonDelete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/admins',
            'controller' => AdminController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/admins/{id}',
            'controller' => AdminController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/admins',
            'controller' => AdminController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/admins/{id}',
            'controller' => AdminController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/admins/{id}',
            'controller' => AdminController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/users',
            'controller' => UserController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/users/{id}',
            'controller' => UserController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/users',
            'controller' => UserController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/users/{id}',
            'controller' => UserController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/users/{id}',
            'controller' => UserController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/customers-search',
            'controller' => UserController::class,
            'action' => 'customerSearch',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/user-groups',
            'controller' => UserGroupController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/user-groups/{id}',
            'controller' => UserGroupController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/user-groups',
            'controller' => UserGroupController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/user-groups/{id}',
            'controller' => UserGroupController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/user-groups/{id}',
            'controller' => UserGroupController::class,
            'action' => 'delete',
        ],

        [
            'method' => 'POST',
            'uri' => '/api/user-import',
            'controller' => UserController::class,
            'action' => 'import',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/user-export',
            'controller' => UserController::class,
            'action' => 'export',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/models',
            'controller' => ModelController::class,
            'action' => 'getModels',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/models',
            'controller' => ModelController::class,
            'action' => 'getFields',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/models/table-columns',
            'controller' => ModelController::class,
            'action' => 'getTableColumns',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/models/related-models',
            'controller' => ModelController::class,
            'action' => 'getRelatedModels',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/models/join-table-columns',
            'controller' => ModelController::class,
            'action' => 'getJoinedTableColumns',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/components',
            'controller' => ComponentController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/components/{id}',
            'controller' => ComponentController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/components',
            'controller' => ComponentController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/components/{id}',
            'controller' => ComponentController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/components/{id}',
            'controller' => ComponentController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/component-items',
            'controller' => ComponentController::class,
            'action' => 'indexItem',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/component-items/{id}',
            'controller' => ComponentController::class,
            'action' => 'showItem',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/component/add-items',
            'controller' => ComponentController::class,
            'action' => 'addComponentItem',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/component/update-items/{id}',
            'controller' => ComponentController::class,
            'action' => 'updateComponentItem',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/component/delete-items/{id}',
            'controller' => ComponentController::class,
            'action' => 'deleteItem',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/types',
            'controller' => ListController::class,
            'action' => 'types',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/sites',
            'controller' => ListController::class,
            'action' => 'sites',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/manufacturers',
            'controller' => ListController::class,
            'action' => 'manufacturers',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/vendors',
            'controller' => ListController::class,
            'action' => 'vendors',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/product-tags',
            'controller' => ListController::class,
            'action' => 'productTags',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/product-finishes',
            'controller' => ListController::class,
            'action' => 'productFinishes',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-tags',
            'controller' => TaxonomyController::class,
            'action' => 'getProductTags',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-tags/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'showProductTag',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/product-tags',
            'controller' => TaxonomyController::class,
            'action' => 'createProductTag',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/product-tags/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'updateProductTag',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/product-tags/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'deleteProductTag',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-finishes',
            'controller' => TaxonomyController::class,
            'action' => 'getProductFinishes',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/product-finishes/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'showProductFinish',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/product-finishes',
            'controller' => TaxonomyController::class,
            'action' => 'createProductFinish',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/product-finishes/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'updateProductFinish',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/product-finishes/{id}',
            'controller' => TaxonomyController::class,
            'action' => 'deleteProductFinish',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/list/post-tags',
            'controller' => ListController::class,
            'action' => 'postTags',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/quotes',
            'controller' => QuoteController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/quotes/{id}',
            'controller' => QuoteController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/quotes',
            'controller' => QuoteController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/quotes/{id}',
            'controller' => QuoteController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/quotes/{id}',
            'controller' => QuoteController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/quote-items',
            'controller' => QuoteItemController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/quote-items/{id}',
            'controller' => QuoteItemController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/quotes/add-items',
            'controller' => QuoteItemController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/quote-items/{id}',
            'controller' => QuoteItemController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/quote-items/{id}',
            'controller' => QuoteItemController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/items-product-list',
            'controller' => QuoteItemController::class,
            'action' => 'productList',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/orders',
            'controller' => OrderController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/orders/{id}',
            'controller' => OrderController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/orders',
            'controller' => OrderController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/orders/{id}',
            'controller' => OrderController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/orders/{id}',
            'controller' => OrderController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/order-items',
            'controller' => OrderItemController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/order-items/{id}',
            'controller' => OrderItemController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/order-items',
            'controller' => OrderItemController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/order-items/{id}',
            'controller' => OrderItemController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/order-items/{id}',
            'controller' => OrderItemController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/jobs',
            'controller' => JobController::class,
            'action' => 'jobList',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/jobs/{id}',
            'controller' => JobController::class,
            'action' => 'jobDetails',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/coupons',
            'controller' => CouponController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/coupons/{id}',
            'controller' => CouponController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/coupons',
            'controller' => CouponController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/coupons/{id}',
            'controller' => CouponController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/coupons/{id}',
            'controller' => CouponController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/coupon-products',
            'controller' => CouponItemController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/coupon-products/{id}',
            'controller' => CouponItemController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/coupon-products',
            'controller' => CouponItemController::class,
            'action' => 'create',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/items-product-list/{id}',
            'controller' => CouponItemController::class,
            'action' => 'productList',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pinboards',
            'controller' => PinboardController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pinboards/{id}',
            'controller' => PinboardController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/pinboards',
            'controller' => PinboardController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/pinboards/{id}',
            'controller' => PinboardController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/pinboards/{id}',
            'controller' => PinboardController::class,
            'action' => 'delete',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pinboard-items',
            'controller' => PinboardItemController::class,
            'action' => 'index',
        ],
        [
            'method' => 'GET',
            'uri' => '/api/pinboard-items/{id}',
            'controller' => PinboardItemController::class,
            'action' => 'show',
        ],
        [
            'method' => 'POST',
            'uri' => '/api/pinboard-items',
            'controller' => PinboardItemController::class,
            'action' => 'create',
        ],
        [
            'method' => 'PUT',
            'uri' => '/api/pinboard-items/{id}',
            'controller' => PinboardItemController::class,
            'action' => 'update',
        ],
        [
            'method' => 'DELETE',
            'uri' => '/api/pinboard-items/{id}',
            'controller' => PinboardItemController::class,
            'action' => 'delete',
        ]
    ];
    public static function registerRoutes(){
        Event::on(Route::class, 'add-routes', __CLASS__, function($routes){
            return [array_merge($routes, self::$routes)];
        }, 20);
    }
}
